### ISSUE TITLE
Messaging with Rails and Mailboxer

### ISSUE THREAD

**Issue by ajazshaik** [bodrovis/SitePoint-Mailboxer#8]
It is a pretty good app, but when i tried to develop this app in rails-5 it is giving a lot of errors.

**Comment by bodrovis** [comment]
Well, that's because the article is written for Rails 3 and 4. At the time of writing Rails 5 was not even in beta and I could not forsee what changes were on the way. Still, I have to admit that me and my student did manage to upgrade one of his apps with mailboxer to rails 5, though it was a pain.

**Comment by ajazshaik** [comment]
Thanks for reply, can u please update the tutorial with rails 5?
